In [79]:
import seaborn as sns;sns.set_theme()
import matplotlib.pyplot as plt
# % matplotlib inline
import pandas as pd
import numpy as np

csv_path = "../sci_op/data-overhead/overheads.csv"

df = pd.read_csv(csv_path)
df.columns

df.columns = ['Input Dimension', 'Number of Parties', 'Sample Fraction', 'Affinity Metric', 'Execution Time(S)', 'Comm. Cost(MB)', 'Rounds']

distance_map = {
    0: "Euclidean",
    1: "Manhattan"
}
df['Comm. Cost(MB)'] = df['Comm. Cost(MB)'] / 1024 / 1024
df['Affinity Metric'] = df['Affinity Metric'].replace(distance_map)
df['Execution Time(S)'] = df['Execution Time(S)'] / 1000

def comm_party(dimension: int = 79510):
    df_demo = df[df['Input Dimension']==dimension] #79510
    # print(df_demo)
    ax = sns.barplot(x="Number of Parties", y="Comm. Cost(MB)", data=df_demo, errwidth=0.0, palette="Blues", hue = 'Affinity Metric')
    plt.yscale('symlog')
    # plt.cla()

def comm_dimension(parties: int = 100):
    df_demo = df[df['Number of Parties'] == parties]
    # df_demo = df_demo[df_demo['Affinity Metric'] == 'Manhattan']
    ax = sns.barplot(x='Input Dimension', y='Comm. Cost(MB)', data=df_demo, errwidth=0.0, palette="Blues", hue = 'Affinity Metric')
    plt.yscale('symlog')
    # plt.cla()
# comm_dimension(parties=100)
config_map = {
    "comm": "Comm. Cost(MB)",
    "time": "Execution Time(S)",
    "rounds": "Rounds" 
}

def save_a_kind(kind: str):
    dimensions = [79, 795, 7951, 79510]
    parties = [10, 25, 50, 100]
    prefix = "overheads/" + kind + "-"
    for d in dimensions:
        df_demo = df[df['Input Dimension'] == d]
        ax = sns.barplot(x="Number of Parties", y=config_map[kind], data=df_demo, errwidth=0.0, palette="Blues", hue = 'Affinity Metric')
        plt.yscale('symlog')
        name = prefix + "party-" + str(d)
        plt.savefig(name, dpi=600)
        plt.cla()
    
    for p in parties:
        df_demo = df[df['Number of Parties'] == p]
        ax = sns.barplot(x="Input Dimension", y=config_map[kind], data=df_demo, errwidth=0.0, palette="Blues", hue = 'Affinity Metric')
        plt.yscale('symlog')
        name = prefix + "dimension-" + str(p)
        plt.savefig(name, dpi=600)
        plt.cla()

def save_all_figs():
    for key in config_map.keys():
        save_a_kind(key)
    # for comm
    # for time
    # for rounds

# save_all_figs()

In [84]:
def comm_cmp(d: int = 79510, party: int = 100):
    df_party = df[df["Input Dimension"] == d]
    print("fix dimenson " + str(d), "SED vs SMD: ")
    print("comm:")
    cmp(df_party)
    print("time:")
    res2 = cmp(df_party, kind="Execution Time(S)")
    print(np.mean(res2))

    df_dim = df[df['Number of Parties'] == party]
    print("fix parties " + str(party), "SED vs SMD: ")
    print("comm:")
    cmp(df_dim)
    print("time:")
    res4 = cmp(df_dim, kind="Execution Time(S)")
    print(np.mean(res4))

def cmp(df_party, kind="Comm. Cost(MB)"):
    df_1 = df_party[df_party['Affinity Metric'] == "Euclidean"][kind]# / df_party[df_party['Affinity Metric'] == "Manhattan"]["Comm. Cost(MB)"])
    df_2 = df_party[df_party['Affinity Metric'] == "Manhattan"][kind]# / df_party[df_party['Affinity Metric'] == "Manhattan"]["Comm. Cost(MB)"])
    df_1 = np.array(df_1)
    df_2 = np.array(df_2)
    ret = df_1/df_2
    print(ret)
    return ret

comm_cmp()
    

# sns.barplot(x="NuMBer of Parties", y="Comm. Cost(MB)", data=df_demo, errwidth=0.0, palette="Blues")

fix dimenson 79510 SED vs SMD: 
comm:
[9.23087982 9.23087982 9.23087982 9.23087982 9.23087982]
time:
[2.67518125 2.66876924 2.66974963 2.68172276 2.65970799]
2.6710261736502274
fix parties 100 SED vs SMD: 
comm:
[9.23087982 9.3653267  9.93309359 5.78133413]
time:
[2.67518125 2.45726363 2.33377163 2.76649064]
2.5581767879362185
